### ISSUE TITLE
Support for Azure pipelines

### ISSUE THREAD

**Issue by joerick** [joerick/cibuildwheel#116]
Microsoft's Azure pipelines could be a fantastic option for building wheels

https://azure.microsoft.com/en-gb/services/devops/pipelines/

They do Mac, Windows and Linux in one service, and it's free for OSS.

![image](https://user-images.githubusercontent.com/1244307/50347100-643e1180-052c-11e9-9927-98c04c64a76e.png)

I haven't tried it yet, but it looks very promising!

**Comment by YannickJadoul** [comment]
This looks quite cool, but I am myself somehow not very eager to start fiddling with Microsoft services :-P

**Comment by YannickJadoul** [comment]
Wow, that sounds positive :-)
If you want some help, I could probably give this a try on my project, next week, to have some feedback?

**Comment by astrofrog** [comment]
+1 for Azure, I tried setting it up today and ran into:

```
2019-01-07T16:47:29.0723096Z Traceback (most recent call last):
2019-01-07T16:47:29.0723204Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\runpy.py", line 193, in _run_module_as_main
2019-01-07T16:47:29.0723337Z     "__main__", mod_spec)
2019-01-07T16:47:29.0723465Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\runpy.py", line 85, in _run_code
2019-01-07T16:47:29.0723588Z     exec(code, run_globals)
2019-01-07T16:47:29.0723696Z   File "C:\Users\VssAdministrator\.conda\envs\wheels\Scripts\autowheel.exe\__main__.py", line 9, in <module>
2019-01-07T16:47:29.0724221Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\site-packages\click\core.py", line 764, in __call__
2019-01-07T16:47:29.0725709Z     return self.main(*args, **kwargs)
2019-01-07T16:47:29.0725840Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\site-packages\click\core.py", line 717, in main
2019-01-07T16:47:29.0725986Z     rv = self.invoke(ctx)
2019-01-07T16:47:29.0726134Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\site-packages\click\core.py", line 956, in invoke
2019-01-07T16:47:29.0726284Z     return ctx.invoke(self.callback, **ctx.params)
2019-01-07T16:47:29.0726412Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\site-packages\click\core.py", line 555, in invoke
2019-01-07T16:47:29.0726552Z     return callback(*args, **kwargs)
2019-01-07T16:47:29.0726704Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\site-packages\autowheel\autowheel.py", line 143, in main
2019-01-07T16:47:29.0726824Z     ignore_existing=ignore_existing)
2019-01-07T16:47:29.0726994Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\site-packages\autowheel\autowheel.py", line 116, in process
2019-01-07T16:47:29.0727145Z     sys.exit(cibuildwheel())
2019-01-07T16:47:29.0727293Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\site-packages\cibuildwheel\__main__.py", line 164, in main
2019-01-07T16:47:29.0727418Z     cibuildwheel.windows.build(**build_options)
2019-01-07T16:47:29.0727570Z   File "c:\users\vssadministrator\.conda\envs\wheels\lib\site-packages\cibuildwheel\windows.py", line 51, in build
2019-01-07T16:47:29.0727725Z     assert os.path.exists(os.path.join(config.path, 'python.exe'))
```

But otherwise it works very nicely for Linux and MacOS X

**Comment by astrofrog** [comment]
@joerick - it does seem that ``UsePythonVersion@0`` supports 32-bit Python on Windows:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops

```
- task: UsePythonVersion@0
  inputs:
    #versionSpec: '3.x' 
    #addToPath: true 
    #architecture: 'x64' # Options: x86, x64 (this argument applies only on Windows agents)
```

so maybe it's now possible to do this properly?

**Comment by henryiii** [comment]
You might want to look at what I'm doing here:  <https://github.com/scikit-hep/boost-histogram>. All the files are in `.ci`.  It was designed to be reusable with the rest of SciKit-HEP, so it should read well.

I'm building wheels on Azure for all three OSs, including C++14 support and 32 bit. Python 2.7 on Windows was a pain! But it's working now.

I am very impressed by Azure. Multiple build and release pipelines, and artifacts are great, and it's easy to configure. (Release pipelines are in the UI, but you don't need to see that as part of this work; it just pushes artifacts to PyPI).

**Comment by YannickJadoul** [comment]
I think this can be closed, @joerick? I didn't follow the whole Azure pipelines discussion/implementation, though, so it's better if you decide to close it.

**Comment by joerick** [comment]
Thanks @yannickjadoul, yes the work is complete.

**Comment by joerick** [comment]
Thanks @henryiii for the reference.  I keep meaning to see how release pipelines might fit but I get lost in the UI. :/
