### ISSUE TITLE
cibuildwheel 1.0.0 causes failing windows builds

### ISSUE THREAD

**Issue by djhoese** [joerick/cibuildwheel#206]
See build here: https://dev.azure.com/vispy/vispy/_build/results?buildId=206

Noticed pull requests on my project started failing today with unrelated errors. The related output is below. From what I can tell it looks like the python/pip that is supposed to be used isn't being used and it's resulting in pip trying to install files in system directories.

<details>

```
Executing nuget actions took 5.87 sec
+ C:/cibw/python\pythonx86.3.8.0\tools\python.exe C:\cibw\get-pip.py
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
Installing collected packages: pip, wheel
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
  WARNING: The scripts pip.exe, pip3.8.exe and pip3.exe are installed in 'C:\cibw\python\pythonx86.3.8.0\tools\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wheel.exe is installed in 'C:\cibw\python\pythonx86.3.8.0\tools\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-19.3.1 wheel-0.33.6
+ python --version
Python 3.8.0
+ python -c "import struct; print(struct.calcsize('P') * 8)"
32
+ python -m pip install --upgrade pip
Requirement already up-to-date: pip in c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages (19.3.1)
+ pip install --upgrade setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/d9/de/554b6310ac87c5b921bc45634b07b11394fe63bc4cb5176f5240addf18ab/setuptools-41.6.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 41.2.0
    Uninstalling setuptools-41.2.0:
      Successfully uninstalled setuptools-41.2.0
Successfully installed setuptools-41.6.0
+ pip install wheel
Requirement already satisfied: wheel in c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages (0.33.6)
+ pip install -U numpy Cython jupyter ipywidgets
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/66/d7/b90626aa4dcaeb253095bd4fd3893cd3998eeb8c3f7c8ddd976337d0c4e5/numpy-1.17.3-cp38-cp38-win32.whl (10.8MB)
Collecting Cython
  Downloading https://files.pythonhosted.org/packages/22/03/510503cfbf20f62810a9548c9be13ab86181f00cca9a3a56717c4595d952/Cython-0.29.14-cp38-cp38-win32.whl (1.6MB)
Collecting jupyter
  Using cached https://files.pythonhosted.org/packages/83/df/0f5dd132200728a86190397e1ea87cd76244e42d39ec5e88efd25b2abd7e/jupyter-1.0.0-py2.py3-none-any.whl
Collecting ipywidgets
  Using cached https://files.pythonhosted.org/packages/56/a0/dbcf5881bb2f51e8db678211907f16ea0a182b232c591a6d6f276985ca95/ipywidgets-7.5.1-py2.py3-none-any.whl
Collecting nbconvert
  Using cached https://files.pythonhosted.org/packages/79/6c/05a569e9f703d18aacb89b7ad6075b404e8a4afde2c26b73ca77bb644b14/nbconvert-5.6.1-py2.py3-none-any.whl
Collecting ipykernel
  Using cached https://files.pythonhosted.org/packages/e1/92/8fec943b5b81078399f969f00557804d884c96fcd0bc296e81a2ed4fd270/ipykernel-5.1.3-py3-none-any.whl
Collecting jupyter-console
  Using cached https://files.pythonhosted.org/packages/cb/ee/6374ae8c21b7d0847f9c3722dcdfac986b8e54fa9ad9ea66e1eb6320d2b8/jupyter_console-6.0.0-py2.py3-none-any.whl
Collecting notebook
  Using cached https://files.pythonhosted.org/packages/f5/69/d2ffaf7efc20ce47469187e3a41e6e03e17b45de5a6559f4e7ab3eace5e1/notebook-6.0.2-py3-none-any.whl
Collecting qtconsole
  Using cached https://files.pythonhosted.org/packages/d0/fc/4936c60be8d56acedfefcc13cf9f3d881e4036147d78e86160463c92d1b7/qtconsole-4.5.5-py2.py3-none-any.whl
Collecting traitlets>=4.3.1
  Using cached https://files.pythonhosted.org/packages/ca/ab/872a23e29cec3cf2594af7e857f18b687ad21039c1f9b922fac5b9b142d5/traitlets-4.3.3-py2.py3-none-any.whl
Collecting ipython>=4.0.0; python_version >= "3.3"
  Using cached https://files.pythonhosted.org/packages/81/2e/59cdacea6476a4c21b7c090a91250ffbcd085900f5eb9f4e4d68dd2ee4e3/ipython-7.9.0-py3-none-any.whl
Collecting nbformat>=4.2.0
  Using cached https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl
Collecting widgetsnbextension~=3.5.0
  Using cached https://files.pythonhosted.org/packages/6c/7b/7ac231c20d2d33c445eaacf8a433f4e22c60677eb9776c7c5262d7ddee2d/widgetsnbextension-3.5.1-py2.py3-none-any.whl
Collecting defusedxml
  Using cached https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl
Collecting pygments
  Using cached https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl
Collecting testpath
  Using cached https://files.pythonhosted.org/packages/1b/9e/1a170feaa54f22aeb5a5d16c9015e82234275a3c8ab630b552493f9cb8a9/testpath-0.4.4-py2.py3-none-any.whl
Collecting jupyter-core
  Using cached https://files.pythonhosted.org/packages/fb/82/86437f661875e30682e99d04c13ba6c216f86f5f6ca6ef212d3ee8b6ca11/jupyter_core-4.6.1-py2.py3-none-any.whl
Collecting mistune<2,>=0.8.1
  Using cached https://files.pythonhosted.org/packages/09/ec/4b43dae793655b7d8a25f76119624350b4d65eb663459eb9603d7f1f0345/mistune-0.8.4-py2.py3-none-any.whl
Collecting entrypoints>=0.2.2
  Using cached https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl
Collecting bleach
  Using cached https://files.pythonhosted.org/packages/ab/05/27e1466475e816d3001efb6e0a85a819be17411420494a1e602c36f8299d/bleach-3.1.0-py2.py3-none-any.whl
Collecting pandocfilters>=1.4.1
  Using cached https://files.pythonhosted.org/packages/4c/ea/236e2584af67bb6df960832731a6e5325fd4441de001767da328c33368ce/pandocfilters-1.4.2.tar.gz
Collecting jinja2>=2.4
  Using cached https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl
Collecting tornado>=4.2
  Downloading https://files.pythonhosted.org/packages/30/78/2d2823598496127b21423baffaa186b668f73cd91887fcef78b6eade136b/tornado-6.0.3.tar.gz (482kB)
Collecting jupyter-client
  Using cached https://files.pythonhosted.org/packages/13/81/fe0eee1bcf949851a120254b1f530ae1e01bdde2d3ab9710c6ff81525061/jupyter_client-5.3.4-py2.py3-none-any.whl
Collecting prompt-toolkit<2.1.0,>=2.0.0
  Using cached https://files.pythonhosted.org/packages/87/61/2dfea88583d5454e3a64f9308a686071d58d59a55db638268a6413e1eb6d/prompt_toolkit-2.0.10-py3-none-any.whl
Collecting pyzmq>=17
  Downloading https://files.pythonhosted.org/packages/7a/d2/1eb3a994374802b352d4911f3317313a5b4ea786bc830cc5e343dad9b06d/pyzmq-18.1.0.tar.gz (1.2MB)
Collecting prometheus-client
  Using cached https://files.pythonhosted.org/packages/b3/23/41a5a24b502d35a4ad50a5bb7202a5e1d9a0364d0c12f56db3dbf7aca76d/prometheus_client-0.7.1.tar.gz
Collecting terminado>=0.8.1
  Using cached https://files.pythonhosted.org/packages/a7/56/80ea7fa66565fa75ae21ce0c16bc90067530e5d15e48854afcc86585a391/terminado-0.8.2-py2.py3-none-any.whl
Collecting Send2Trash
  Using cached https://files.pythonhosted.org/packages/49/46/c3dc27481d1cc57b9385aff41c474ceb7714f7935b1247194adae45db714/Send2Trash-1.5.0-py3-none-any.whl
Collecting ipython-genutils
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting decorator
  Using cached https://files.pythonhosted.org/packages/8f/b7/f329cfdc75f3d28d12c65980e4469e2fa373f1953f5df6e370e84ea2e875/decorator-4.4.1-py2.py3-none-any.whl
Collecting six
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting backcall
  Using cached https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz
Collecting jedi>=0.10
  Using cached https://files.pythonhosted.org/packages/55/54/da994f359e4e7da4776a200e76dbc85ba5fc319eefc22e33d55296d95a1d/jedi-0.15.1-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32"
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: setuptools>=18.5 in c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (41.6.0)
Collecting pickleshare
  Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting jsonschema!=2.5.0,>=2.4
  Using cached https://files.pythonhosted.org/packages/ce/6c/888d7c3c1fce3974c88a01a6bc553528c99d3586e098eee23e8383dd11c3/jsonschema-3.1.1-py2.py3-none-any.whl
Collecting pywin32>=1.0; sys_platform == "win32"
  Downloading https://files.pythonhosted.org/packages/ea/bd/a87a75287eb1e91cf31045fef7465eb8e25cfd91629f16fbfb2035b194c7/pywin32-226-cp38-cp38-win32.whl (8.4MB)
Collecting webencodings
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23
  Downloading https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz
Collecting python-dateutil>=2.1
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting wcwidth
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting pywinpty>=0.5; os_name == "nt"
  Downloading https://files.pythonhosted.org/packages/21/ae/acbedcee475d049647e45ee949e23ca492764fcd8027a073fcf07646d47c/pywinpty-0.5.5.tar.gz (48kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\cibw\python\pythonx86.3.8.0\tools\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pip-install-3emjg2yi\\pywinpty\\setup.py'"'"'; __file__='"'"'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pip-install-3emjg2yi\\pywinpty\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-3emjg2yi\pywinpty\pip-egg-info'
         cwd: C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-3emjg2yi\pywinpty\
    Complete output (147 lines):
    Unable to find pgen, not compiling formal grammar.
    Traceback (most recent call last):
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
        self.run_command("egg_info")
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\command\egg_info.py", line 283, in run
        self.mkpath(self.egg_info)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\distutils\cmd.py", line 338, in mkpath
        dir_util.mkpath(name, mode, dry_run=self.dry_run)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\distutils\dir_util.py", line 70, in mkpath
        os.mkdir(head, mode)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 310, in wrap
        path = self._remap_input(name, path, *args, **kw)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 452, in _remap_input
        self._violation(operation, os.path.realpath(path), *args, **kw)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 407, in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\easy_install-df4grjgq\\Cython-0.29.14\\Cython.egg-info', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\VSSADM~1\AppData\Local\Temp\easy_install-df4grjgq\Cython-0.29.14\setup.py", line 228, in <module>
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\easy_install-df4grjgq\\Cython-0.29.14\\Cython.egg-info', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\VSSADM~1\AppData\Local\Temp\easy_install-df4grjgq\Cython-0.29.14\setup.py", line 228, in <module>
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\easy_install-df4grjgq\\Cython-0.29.14\\Cython.egg-info', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-3emjg2yi\pywinpty\setup.py", line 68, in <module>
        setup(
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\dist.py", line 717, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\dist.py", line 787, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\cibw\python\pythonx86.3.8.0\tools\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\easy_install-df4grjgq\\Cython-0.29.14\\Cython.egg-info', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.7.5\x64\Scripts\cibuildwheel.exe\__main__.py", line 7, in <module>
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\site-packages\cibuildwheel\__main__.py", line 176, in main
    cibuildwheel.windows.build(**build_options)
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\site-packages\cibuildwheel\windows.py", line 140, in build
    shell([before_build_prepared], env=env)
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\site-packages\cibuildwheel\windows.py", line 65, in simple_shell
    return subprocess.check_call(' '.join(args), env=env, cwd=cwd)
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmd /E:ON /V:ON /C pip install -U numpy Cython jupyter ipywidgets' returned non-zero exit status 1.
```

</details>

**Comment by mayeut** [comment]
It seems that `pywinpty` is the culprit here, not `cibuildwheel`. Before `cibuildwheel` 1.0.0, python 3.8.0 was not built. `pywinpty` has wheels for those previous python versions but not `3.8`.
c.f. https://github.com/spyder-ide/pywinpty/issues/123
You're not directly hitting this issue because of the weird issue you're getting with Cython install during `pywinpty` but would hit this issue otherwise. I will check over at pip issue tracker this weird behavior though.
In the meantime, you can skip python 3.8 on windows with `CIBW_SKIP=cp38-win*`

**Comment by mayeut** [comment]
The weird SandboxViolation seems to come from `setuptools`, also related to python 3.8: https://github.com/pypa/setuptools/issues/1874

**Comment by joerick** [comment]
Hm, it is a weird one! If the error is caused by installing dependencies with easy_install, it might be worked around by installing with pip by doing `CIBW_BEFORE_BUILD="pip install ."`? Just an idea. But if pywinpty doesn't support 3.8 yet, that's a bigger problem.

**Comment by djhoese** [comment]
@joerick I'm not explicitly using easy_install anywhere. Any ideas why pywinpty would be using it? Or does pip still end up getting to easy_install.py during its normal operation?

**Comment by joerick** [comment]
I think that if you're including something using `setup_requires`, it causes setuptools to fetch the dependency itself, rather than using pip.  `setup_requires` often causes random issues, sometimes if possible it's better to just chuck em all in `install_requires` and install the package before doing anything.

**Comment by joerick** [comment]
Closing due to inactivity. Feel free to reopen if this is still a problem, especially outside the use of `setup_requires`.

**Comment by djhoese** [comment]
I'm ok with closing this. I don't remember what I did, but I think this got resolved. Also new versions of pip, if I remember correctly, have now dropped easy_install completely.
