### ISSUE TITLE
manylinux build failing with unable to find image

### ISSUE THREAD

**Issue by davidism** [joerick/cibuildwheel#357]
MarkupSafe Linux builds stopped working today with the error:

```
+ docker create --env CIBUILDWHEEL --name cibuildwheel-29afbfcb-daa8-4d72-af75-47fc97b09662 -i -v /:/host quay.io/pypa/manylinux2010_x86_64:2020-05-20-c7bbd11 /bin/bash
Unable to find image 'quay.io/pypa/manylinux2010_x86_64:2020-05-20-c7bbd11' locally
Error response from daemon: Get https://quay.io/v2/: EOF
+ docker rm --force -v cibuildwheel-29afbfcb-daa8-4d72-af75-47fc97b09662
Error: No such container: cibuildwheel-29afbfcb-daa8-4d72-af75-47fc97b09662
```

Config: https://github.com/pallets/markupsafe/blob/49ba2ffe23ee3a15ddab9e5c108d0b0dbbb0ca1e/.github/workflows/build.yaml
Failing run: https://github.com/pallets/markupsafe/runs/717426335#step:5:1

This sounds like it might be a temporary availability issue with Quay or manylinux, but I wanted to check if you had seen this or if this was something I needed to fix.

<details><summary>full log</summary>

```
2020-05-28T16:00:05.8693319Z 
2020-05-28T16:00:05.8695792Z      _ _       _ _   _       _           _
2020-05-28T16:00:05.8697930Z  ___|_| |_ _ _|_| |_| |_ _ _| |_ ___ ___| |
2020-05-28T16:00:05.8700121Z |  _| | . | | | | | . | | | |   | -_| -_| |
2020-05-28T16:00:05.8700251Z |___|_|___|___|_|_|___|_____|_|_|___|___|_|
2020-05-28T16:00:05.8700339Z 
2020-05-28T16:00:05.8700443Z cibuildwheel version 1.4.2
2020-05-28T16:00:05.8700566Z 
2020-05-28T16:00:05.8700685Z Build options:
2020-05-28T16:00:05.8700958Z   platform: 'linux'
2020-05-28T16:00:05.8703262Z   before_build: None
2020-05-28T16:00:05.8703698Z   before_test: ''
2020-05-28T16:00:05.8704167Z   build_selector: BuildSelector('*' - 'cp27-* pp27-* cp35-*')
2020-05-28T16:00:05.8704318Z   build_verbosity: 0
2020-05-28T16:00:05.8704462Z   dependency_constraints: <cibuildwheel.util.DependencyConstraints object at 0x7f70c498a6d0>
2020-05-28T16:00:05.8706141Z   environment: ParsedEnvironment([])
2020-05-28T16:00:05.8707601Z   manylinux_images: {'x86_64': 'quay.io/pypa/manylinux2010_x86_64:2020-05-20-c7bbd11', 'i686': 'quay.io/pypa/manylinux2010_i686:2020-05-20-c7bbd11', 'pypy_x86_64': 'pypywheels/manylinux2010-pypy_x86_64:2020-04-25-eb2cdff', 'aarch64': 'quay.io/pypa/manylinux2014_aarch64:2020-05-17-2f8ac3b', 'ppc64le': 'quay.io/pypa/manylinux2014_ppc64le:2020-05-17-2f8ac3b', 's390x': 'quay.io/pypa/manylinux2014_s390x:2020-05-17-2f8ac3b'}
2020-05-28T16:00:05.8708554Z   output_dir: 'wheelhouse'
2020-05-28T16:00:05.8709073Z   package_dir: '.'
2020-05-28T16:00:05.8709670Z   repair_command: 'auditwheel repair -w {dest_dir} {wheel}'
2020-05-28T16:00:05.8710042Z   test_command: None
2020-05-28T16:00:05.8710554Z   test_extras: ''
2020-05-28T16:00:05.8710911Z   test_requires: []
2020-05-28T16:00:05.8711173Z 
2020-05-28T16:00:05.8711492Z Here we go!
2020-05-28T16:00:05.8711751Z 
2020-05-28T16:00:11.1241613Z Docker version 3.0.11+azure, build eb310fca49568dccd87c6136f774ef6fff2a1b51
2020-05-28T16:00:11.1253473Z + docker create --env CIBUILDWHEEL --name cibuildwheel-29afbfcb-daa8-4d72-af75-47fc97b09662 -i -v /:/host quay.io/pypa/manylinux2010_x86_64:2020-05-20-c7bbd11 /bin/bash
2020-05-28T16:00:11.4443147Z Unable to find image 'quay.io/pypa/manylinux2010_x86_64:2020-05-20-c7bbd11' locally
2020-05-28T16:00:11.5336730Z Error response from daemon: Get https://quay.io/v2/: EOF
2020-05-28T16:00:11.5367755Z + docker rm --force -v cibuildwheel-29afbfcb-daa8-4d72-af75-47fc97b09662
2020-05-28T16:00:11.6162211Z Error: No such container: cibuildwheel-29afbfcb-daa8-4d72-af75-47fc97b09662
2020-05-28T16:00:11.6618583Z Traceback (most recent call last):
2020-05-28T16:00:11.6620845Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/cibuildwheel/linux.py", line 121, in build
2020-05-28T16:00:11.6621377Z     call(['docker', 'create',
2020-05-28T16:00:11.6621950Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/cibuildwheel/linux.py", line 21, in call
2020-05-28T16:00:11.6622156Z     subprocess.run(
2020-05-28T16:00:11.6622374Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/subprocess.py", line 512, in run
2020-05-28T16:00:11.6622617Z     raise CalledProcessError(retcode, process.args,
2020-05-28T16:00:11.6623360Z subprocess.CalledProcessError: Command '['docker', 'create', '--env', 'CIBUILDWHEEL', '--name', 'cibuildwheel-29afbfcb-daa8-4d72-af75-47fc97b09662', '-i', '-v', '/:/host', 'quay.io/pypa/manylinux2010_x86_64:2020-05-20-c7bbd11', '/bin/bash']' returned non-zero exit status 1.
2020-05-28T16:00:11.6623561Z 
2020-05-28T16:00:11.6623721Z During handling of the above exception, another exception occurred:
2020-05-28T16:00:11.6623814Z 
2020-05-28T16:00:11.6624217Z Traceback (most recent call last):
2020-05-28T16:00:11.6624802Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/cibuildwheel/linux.py", line 279, in build
2020-05-28T16:00:11.6625001Z     exit(1)
2020-05-28T16:00:11.6625221Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/_sitebuiltins.py", line 26, in __call__
2020-05-28T16:00:11.6625417Z     raise SystemExit(code)
2020-05-28T16:00:11.6625571Z SystemExit: 1
2020-05-28T16:00:11.6625664Z 
2020-05-28T16:00:11.6625802Z During handling of the above exception, another exception occurred:
2020-05-28T16:00:11.6625908Z 
2020-05-28T16:00:11.6626036Z Traceback (most recent call last):
2020-05-28T16:00:11.6626256Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/bin/cibuildwheel", line 8, in <module>
2020-05-28T16:00:11.6626453Z     sys.exit(main())
2020-05-28T16:00:11.6627003Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/cibuildwheel/__main__.py", line 228, in main
2020-05-28T16:00:11.6627214Z     cibuildwheel.linux.build(build_options)
2020-05-28T16:00:11.6627769Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/cibuildwheel/linux.py", line 282, in build
2020-05-28T16:00:11.6628203Z     call(['docker', 'rm', '--force', '-v', container_name])
2020-05-28T16:00:11.6628736Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/cibuildwheel/linux.py", line 21, in call
2020-05-28T16:00:11.6628929Z     subprocess.run(
2020-05-28T16:00:11.6629144Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/subprocess.py", line 512, in run
2020-05-28T16:00:11.6629385Z     raise CalledProcessError(retcode, process.args,
2020-05-28T16:00:11.6629959Z subprocess.CalledProcessError: Command '['docker', 'rm', '--force', '-v', 'cibuildwheel-29afbfcb-daa8-4d72-af75-47fc97b09662']' returned non-zero exit status 1.
2020-05-28T16:00:11.6798680Z ##[error]Process completed with exit code 1.
```

</details>

**Comment by davidism** [comment]
Never mind, it's definitely a Quay issue: https://status.quay.io/incidents/qdn3wz80kzww?u=hxgfwz0yyjql

**Comment by YannickJadoul** [comment]
Yup, not `cibuildwheel`. quay.io seems to be getting up again, btw.

It's a bit weird that the second command gets executed while the first fails, though. If I `docker create` a container from an nonexisting image, the return code is non-zero, but I cannot reproduce the exact error (because quay.io is back). @Czaki, any thoughts on why? Should we care, or not?

**Comment by davidism** [comment]
That did make it a bit harder to see the issue at first, since the final error message makes it look like the problem was the container, not getting the image.

**Comment by YannickJadoul** [comment]
Exactly! But as far as I can see, on master, the call is done with `subprocess.run(..., check=True)`, so if docker doesn't return a non-zero error code, there's not a lot we can do, probably :-(

**Comment by Czaki** [comment]
The second command is from finally block:

```
        finally:
            # Still gets executed, even when 'exit(1)' gets called
            call(['docker', 'rm', '--force', '-v', container_name])
```

maybe moving `try` below creating container is good idea, but I do not know if there is possible failture after which cleaning is need.

**Comment by YannickJadoul** [comment]
Oh, yes! Good catch! I had just assumed it was the next docker command; not the one in finally.

If we move `docker create` outside of the try-catch, does it matter if it fails and we don't clean it up?
I can't find anything about exit codes either, in the [docker docs](https://docs.docker.com/engine/reference/commandline/create/).

Or of course, we could check whether the docker container was created through `docker ps -a` before trying to remove it. But that feels too complex, actually.

Another option is to wrap the `docker rm` in a `try: ... except: pass` and just ignore any error from that command.

**Comment by Czaki** [comment]
> Another option is to wrap the `docker rm` in a `try: ... except: pass` and just ignore any error from that command.

I like this.
