### ISSUE TITLE
Travis Windows issue - SSL certificates

### ISSUE THREAD

**Issue by hannesmuehleisen** [joerick/cibuildwheel#456]
Hi all, we are happy users of cibuildwheel, but we recently started seeing a SSL certificate verification issue on Travis (.com) Windows builds. To me, this looks like a certificate verification error with `dist.nuget.org` but I could be mistaken. Any suggestions on how to fix this?

Below an (abridged) log:

````
python -m cibuildwheel --platform windows --output-dir wheelhouse duckdb_tarball

     _ _       _ _   _       _           _
 ___|_| |_ _ _|_| |_| |_ _ _| |_ ___ ___| |
|  _| | . | | | | | . | | | |   | -_| -_| |
|___|_|___|___|_|_|___|_____|_|_|___|___|_|

cibuildwheel version 1.6.3

Build options:
  platform: 'windows'
  before_all: ''
  before_build: 'pip install --prefer-binary "pandas>=0.24" "pytest>=4.3"'
  before_test: 'pip install --prefer-binary "pandas>=0.24"'
  build_selector: BuildSelector('cp36-* cp37-* cp38-*' - '')
  build_verbosity: 0
  dependency_constraints: <cibuildwheel.util.DependencyConstraints object at 0x0000016D04D526D0>
  environment: ParsedEnvironment([])
  manylinux_images: None
  output_dir: WindowsPath('wheelhouse')
  package_dir: WindowsPath('duckdb_tarball')
  repair_command: ''
  test_command: 'python -m pytest {project}/tests'
  test_extras: ''
  test_requires: ['pytest']

Here we go!

+ Download https://dist.nuget.org/win-x86-commandline/latest/nuget.exe to C:\cibw\nuget.exe
Traceback (most recent call last):
[]
  File "C:\Python38\lib\site-packages\cibuildwheel\windows.py", line 200, in build
    download('https://dist.nuget.org/win-x86-commandline/latest/nuget.exe', nuget)
  File "C:\Python38\lib\site-packages\cibuildwheel\util.py", line 72, in download
    response = urllib.request.urlopen(url)
[]...
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

````

**Comment by hannesmuehleisen** [comment]
Nevermind, I fixed it by updating from Python 3.8.0 to 3.8.6

**Comment by joerick** [comment]
Cibuildwheel v1.6.4 should fix this also.

**Comment by hannesmuehleisen** [comment]
> Cibuildwheel v1.6.4 should fix this also.

It did not
