### ISSUE TITLE
Travis CI: pypi upload broken on Linux

### ISSUE THREAD

**Issue by kimwalisch** [joerick/cibuildwheel#463]
Hi,

I am using a [.travis.yml](https://github.com/kimwalisch/primesieve-python/blob/master/.travis.yml) script that is virtually identical to your [travis example-setup](https://github.com/joerick/cibuildwheel#example-setup). Since a few weeks the upload is broken on Linux:

```
$ python3 -m twine upload -p $TEST_TOKEN --repository-url https://test.pypi.org/legacy/ --skip-existing --verbose $UPLOAD_FILES;
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/twine/__main__.py", line 53, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/twine/__main__.py", line 28, in main
   bo result = cli.dispatch(sys.argv[1:])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/twine/cli.py", line 80, in dispatch
    main = registered_commands[args.command].load()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (importlib-metadata 0.18 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('importlib-metadata>=1; python_version < "3.8"'), {'keyring'})
```

The issue seems to be a travis bug, see https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494. Apparently this bug has already been fixed in travis, but the deployment code has changed a little.

Could you please update your [travis example-setup](https://github.com/joerick/cibuildwheel#example-setup)? Unfortunately I cannot help fix this issue as my understanding of travis is not good enough.

**Comment by henryiii** [comment]
I expect this has worked itself out, but maybe it would be better to show the built-in python deploy functionality in the example, rather than doing this manually? With Travis [pulling out of free open source support](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works), it's becoming less motivating to update Travis examples. I do use this [here](https://github.com/scikit-hep/boost-histogram/blob/ff600a0807c3a94208a7b00d8c5086adc17226b9/.travis.yml#L35-L43), so I could update it if we want to do that.

**Comment by kimwalisch** [comment]
I agree, it's time to abandon Travis.

I suggest updating the example code in your README.md to GitHub Actions.

**Comment by joerick** [comment]
> I suggest updating the example code in your README.md to GitHub Actions.

good idea!

**Comment by henryiii** [comment]
I didn't even realize it wasn't... :O
